name: React App Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      # Get repository code
      - name: Checkout repository
        uses: actions/checkout@v4


      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm


      # Install dependencies
      - name: Install dependencies
        run: npm ci


      # Build React application
      - name: Build project
        run: npm run build
